server:
  port: 8042
  servlet:
    context-path: /demo
    session:
      timeout: 120s

content: "port:${server.port},path:${server.servlet.context-path}"

devconfig:
  ip: 127.0.0.1
  port: 12345

spring:
    #redis:
    #      database: 0 # Redis数据库索引（默认为0）
    #      host: 127.0.0.1  #Redis服务器地址
    #      port: 6379 # Redis服务器连接端口
    #      password: # Redis服务器连接密码（默认为空）
    #      pool:
    #        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    #        max-idle: 10 # 连接池中的最大空闲连接
    #        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        min-idle: 5 # 连接池中的最小空闲连接
    #        timeout: 2000 # 连接超时时间（毫秒）
    #mysql配置
    datasource:
        name: Personal
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false
          username: root
          password: '022578'
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    redis:
        host: 127.0.0.1
        port: 6379
        lettuce:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo1.model  # 注意：对应实体类的路径
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
  level:
    com:
      example:
          demo1:
            repository: debug